sudo: required
language: generic 
services: 
  - docker


before_install:
  - docker build -t crimsonknightd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true crimsonknightd/docker-react npm run test